version: '3.8'

services:
  eventmanager.api:
    build:
      context: .
      dockerfile: EventManager.Api/Dockerfile
    image: eventmanager.api
    container_name: eventmanager.api
    ports:
      - "5000:5000"   # HTTP
      - "5001:5001"   # HTTPS
    environment:
      - FILE_STORAGE_PATH=/data/uploads
    volumes:
      - ./data/uploads:/data/uploads
    depends_on:
      eventmanager.database:
        condition: service_healthy
    networks:
      - eventmanager-network

  eventmanager.database:
    image: postgres:latest
    container_name: eventmanager.database
    environment:
      - POSTGRES_DB=EventManagerDataBase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/EventManagerDataBase:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventmanager-network

  eventmanager.cache:
    image: redis:latest
    container_name: eventmanager.redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - eventmanager-network

networks:
  eventmanager-network:
    driver: bridge
