version: '3.8'

name: eventmanager

services:
  eventmanager.api:
    image: ${DOCKER_REGISTRY-}eventmanagerapi
    container_name: eventmanager.api
    build:
      context: .
      dockerfile: EventManager.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./data/uploads:/data/uploads
    environment:
      - FILE_STORAGE_PATH=/data/uploads
    networks:
      - eventmanager-network
  eventmanager.database:
    image: postgres:latest
    container_name: eventmanager.database
    environment:
      - POSTGRES_DB=EventManagerDataBase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/EventManagerDataBase:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
     - eventmanager-network

  eventmanager.cache:
    container_name: eventmanager.redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - eventmanager-network
networks: 
  eventmanager-network:
    driver: bridge
